### ISSUE TITLE
"Could not find builtins" error

### ISSUE THREAD

**Issue by wizzardx** [wizzardx/mypy#1]
With latest dev version of mypy (currently 47b40a77) - since my most recent git pull, I get this error when trying to run mypy:

---
## test.py:1: error: Could not find builtins

Where this is the complete contents of test.py:

---
# !/usr/bin/env python3.4
## print("HELLO WORLD")

And the command-line is:

---
## mypy test.py

(Where I am under a Python virtualenv, where the latest dev version of mypy has been installed).

I ran a git bisect to track down where this issue started, and ended up at this commit where - in my testing - this problem starts manifesting:

---

commit 2c009ca991bf5d1b42741c0d1a2fbf6bb6077cd4
Author: Ben Longbons b.r.longbons@gmail.com
Date:   Tue Jun 30 22:18:20 2015 -0700

```
Move script to mypy.main module and just leave stubs
```

---

This is a breaking issue for me - for now I need to do my dev/testing against the commit prior to that, 2e591dcd11.

Please advise?
